# Generated by Django 3.0 on 2020-03-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('course_id', models.PositiveIntegerField()),
                ('enquiry', models.TextField(max_length=250)),
                ('recommendation', models.CharField(max_length=20)),
            ],
        ),
    ]
